### PR TITLE
updated composer dependencies and removed symfony/thanks package

### PR DESCRIPTION
**Pull request by maximgubar**

### CODE REVIEW

**Comment by dbu** [comment]
seems that phpunit 5.7.zip is gone from github. the bridge should download an explicit patch version like 5.7.25 i guess - not sure if we can make it do that somehow, maybe by explicitly specifying that version?

**Comment by dbu** [comment]
this failure is not related to the change here - i restarted the build of master that was green and now it fails with the same problem.

**Comment by maximgubar** [comment]
@dbu I've updated symfony/phpunit-bridge version to follow master branch.
this isuues was solved there few days ago, but there is no release tag which contains this changes.

**Comment by dbu** [comment]
cheers. its a dev dependency only, so that should be good enough for now

**Pull request merged**
